name: Wishes

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Thursday
  Date_of_month: 2nd March

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Thursday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
